[package]
name = "asterism-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
asterism-node = { path = "../../../crates/asterism-node" }
asterism-proto = { path = "../../../crates/asterism-proto" }
serde_json = "1"
tauri = { version = "2", features = [] }
base64 = "0.22"
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
